package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class eligibleServices implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "medical")
	private java.lang.Boolean medical;
	@org.kie.api.definition.type.Label(value = "towing")
	private java.lang.Boolean towing;
	@org.kie.api.definition.type.Label(value = "roadsideAssist")
	private java.lang.Boolean roadsideAssist;
	@org.kie.api.definition.type.Label(value = "taxi")
	private java.lang.Boolean taxi;
	@org.kie.api.definition.type.Label(value = "carHire")
	private java.lang.Boolean carHire;

	public eligibleServices() {
	}

	public java.lang.Boolean getMedical() {
		return this.medical;
	}

	public void setMedical(java.lang.Boolean medical) {
		this.medical = medical;
	}

	public java.lang.Boolean getTowing() {
		return this.towing;
	}

	public void setTowing(java.lang.Boolean towing) {
		this.towing = towing;
	}

	public java.lang.Boolean getRoadsideAssist() {
		return this.roadsideAssist;
	}

	public void setRoadsideAssist(java.lang.Boolean roadsideAssist) {
		this.roadsideAssist = roadsideAssist;
	}

	public java.lang.Boolean getTaxi() {
		return this.taxi;
	}

	public void setTaxi(java.lang.Boolean taxi) {
		this.taxi = taxi;
	}

	public java.lang.Boolean getCarHire() {
		return this.carHire;
	}

	public void setCarHire(java.lang.Boolean carHire) {
		this.carHire = carHire;
	}

	public eligibleServices(java.lang.Boolean medical,
			java.lang.Boolean towing, java.lang.Boolean roadsideAssist,
			java.lang.Boolean taxi, java.lang.Boolean carHire) {
		this.medical = medical;
		this.towing = towing;
		this.roadsideAssist = roadsideAssist;
		this.taxi = taxi;
		this.carHire = carHire;
	}

}