package com.myteam.tts_connected_claims;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class escalatedServices implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "ESCALATEDSERVICES_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "ESCALATEDSERVICES_ID_SEQ", name = "ESCALATEDSERVICES_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "serviceType")
	private java.lang.String serviceType;

	@org.kie.api.definition.type.Label(value = "serviceSubType")
	private java.lang.String serviceSubType;

	@org.kie.api.definition.type.Label(value = "escalationReason")
	private java.lang.String escalationReason;

	public escalatedServices() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(java.lang.String serviceType) {
		this.serviceType = serviceType;
	}

	public java.lang.String getServiceSubType() {
		return this.serviceSubType;
	}

	public void setServiceSubType(java.lang.String serviceSubType) {
		this.serviceSubType = serviceSubType;
	}

	public java.lang.String getEscalationReason() {
		return this.escalationReason;
	}

	public void setEscalationReason(java.lang.String escalationReason) {
		this.escalationReason = escalationReason;
	}

	public escalatedServices(java.lang.Long id, java.lang.String serviceType,
			java.lang.String serviceSubType, java.lang.String escalationReason) {
		this.id = id;
		this.serviceType = serviceType;
		this.serviceSubType = serviceSubType;
		this.escalationReason = escalationReason;
	}

}