package com.myteam.rulesbase;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class dedupCaseParams implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("policyNumber")
	private java.lang.String policyNumber;

	@org.kie.api.definition.type.Label("vehicleIncidentType")
	private java.lang.String vehicleIncidentType;

	@org.kie.api.definition.type.Label("vehicleIncidentSubtype")
	private java.lang.String vehicleIncidentSubtype;

	@org.kie.api.definition.type.Label("registrationNumber")
	private java.lang.String registrationNumber;

	@org.kie.api.definition.type.Label("riskitemSequenceNumber")
	private java.lang.String riskitemSequenceNumber;

	public dedupCaseParams() {
	}

	public java.lang.String getPolicyNumber() {
		return this.policyNumber;
	}

	public void setPolicyNumber(java.lang.String policyNumber) {
		this.policyNumber = policyNumber;
	}

	public java.lang.String getVehicleIncidentType() {
		return this.vehicleIncidentType;
	}

	public void setVehicleIncidentType(java.lang.String vehicleIncidentType) {
		this.vehicleIncidentType = vehicleIncidentType;
	}

	public java.lang.String getVehicleIncidentSubtype() {
		return this.vehicleIncidentSubtype;
	}

	public void setVehicleIncidentSubtype(
			java.lang.String vehicleIncidentSubtype) {
		this.vehicleIncidentSubtype = vehicleIncidentSubtype;
	}

	public java.lang.String getRegistrationNumber() {
		return this.registrationNumber;
	}

	public void setRegistrationNumber(java.lang.String registrationNumber) {
		this.registrationNumber = registrationNumber;
	}

	public java.lang.String getRiskitemSequenceNumber() {
		return this.riskitemSequenceNumber;
	}

	public void setRiskitemSequenceNumber(
			java.lang.String riskitemSequenceNumber) {
		this.riskitemSequenceNumber = riskitemSequenceNumber;
	}

	public dedupCaseParams(java.lang.String policyNumber,
			java.lang.String vehicleIncidentType,
			java.lang.String vehicleIncidentSubtype,
			java.lang.String registrationNumber,
			java.lang.String riskitemSequenceNumber) {
		this.policyNumber = policyNumber;
		this.vehicleIncidentType = vehicleIncidentType;
		this.vehicleIncidentSubtype = vehicleIncidentSubtype;
		this.registrationNumber = registrationNumber;
		this.riskitemSequenceNumber = riskitemSequenceNumber;
	}

}