package com.myteam.rulesbase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class enableServices implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("incidentType")
	private java.lang.String incidentType;
	@org.kie.api.definition.type.Label("riskItem")
	private java.lang.String riskItem;
	@org.kie.api.definition.type.Label("vehicleIncidentType")
	private java.lang.String vehicleIncidentType;
	@org.kie.api.definition.type.Label("vehicleIncidentSubType")
	private java.lang.String vehicleIncidentSubType;
	@org.kie.api.definition.type.Label("drivable")
	private java.lang.String drivable;
	@org.kie.api.definition.type.Label("towingEnable")
	private java.lang.Boolean towingEnable;
	@org.kie.api.definition.type.Label("roadsideEnable")
	private java.lang.Boolean roadsideEnable;
	@org.kie.api.definition.type.Label("taxiEnable")
	private java.lang.Boolean taxiEnable;

	@org.kie.api.definition.type.Label("recoveryEnable")
	private java.lang.Boolean recoveryEnable;

	@org.kie.api.definition.type.Label("tradeTowEnable")
	private java.lang.Boolean tradeTowEnable;

	@org.kie.api.definition.type.Label(value = "stockEnable")
	private java.lang.Boolean stockEnable;

	public enableServices() {
	}

	public java.lang.String getIncidentType() {
		return this.incidentType;
	}

	public void setIncidentType(java.lang.String incidentType) {
		this.incidentType = incidentType;
	}

	public java.lang.String getRiskItem() {
		return this.riskItem;
	}

	public void setRiskItem(java.lang.String riskItem) {
		this.riskItem = riskItem;
	}

	public java.lang.String getVehicleIncidentType() {
		return this.vehicleIncidentType;
	}

	public void setVehicleIncidentType(java.lang.String vehicleIncidentType) {
		this.vehicleIncidentType = vehicleIncidentType;
	}

	public java.lang.String getVehicleIncidentSubType() {
		return this.vehicleIncidentSubType;
	}

	public void setVehicleIncidentSubType(
			java.lang.String vehicleIncidentSubType) {
		this.vehicleIncidentSubType = vehicleIncidentSubType;
	}

	public java.lang.String getDrivable() {
		return this.drivable;
	}

	public void setDrivable(java.lang.String drivable) {
		this.drivable = drivable;
	}

	public java.lang.Boolean getTowingEnable() {
		return this.towingEnable;
	}

	public void setTowingEnable(java.lang.Boolean towingEnable) {
		this.towingEnable = towingEnable;
	}

	public java.lang.Boolean getRoadsideEnable() {
		return this.roadsideEnable;
	}

	public void setRoadsideEnable(java.lang.Boolean roadsideEnable) {
		this.roadsideEnable = roadsideEnable;
	}

	public java.lang.Boolean getTaxiEnable() {
		return this.taxiEnable;
	}

	public void setTaxiEnable(java.lang.Boolean taxiEnable) {
		this.taxiEnable = taxiEnable;
	}

	public java.lang.Boolean getRecoveryEnable() {
		return this.recoveryEnable;
	}

	public void setRecoveryEnable(java.lang.Boolean recoveryEnable) {
		this.recoveryEnable = recoveryEnable;
	}

	public java.lang.Boolean getTradeTowEnable() {
		return this.tradeTowEnable;
	}

	public void setTradeTowEnable(java.lang.Boolean tradeTowEnable) {
		this.tradeTowEnable = tradeTowEnable;
	}

	public java.lang.Boolean getStockEnable() {
		return this.stockEnable;
	}

	public void setStockEnable(java.lang.Boolean stockEnable) {
		this.stockEnable = stockEnable;
	}

	public enableServices(java.lang.String incidentType,
			java.lang.String riskItem, java.lang.String vehicleIncidentType,
			java.lang.String vehicleIncidentSubType, java.lang.String drivable,
			java.lang.Boolean towingEnable, java.lang.Boolean roadsideEnable,
			java.lang.Boolean taxiEnable, java.lang.Boolean recoveryEnable,
			java.lang.Boolean tradeTowEnable, java.lang.Boolean stockEnable) {
		this.incidentType = incidentType;
		this.riskItem = riskItem;
		this.vehicleIncidentType = vehicleIncidentType;
		this.vehicleIncidentSubType = vehicleIncidentSubType;
		this.drivable = drivable;
		this.towingEnable = towingEnable;
		this.roadsideEnable = roadsideEnable;
		this.taxiEnable = taxiEnable;
		this.recoveryEnable = recoveryEnable;
		this.tradeTowEnable = tradeTowEnable;
		this.stockEnable = stockEnable;
	}

}